document.write("<table border= 1 margin= 0 auto>")
document.write('<tr>')
document.write('<td>Language</td>')
document.write('<td>Locks</td>')
document.write('<td>mediaDevices</td>')
document.write('<td>permissions</td>')
document.write('</tr>')
document.write('<tr>')
document.write(`<td> ${navigator.language} </td>`)
document.write(`<td> ${navigator.locks} </td>`)
document.write(`<td> ${navigator.mediaDevices} </td>`)
document.write(`<td> ${navigator.permissions} </td>`)
document.write('</tr>')
document.write("</table>")